### ISSUE TITLE
discord 通知用の workflow 作成

### ISSUE THREAD

**Issue by ayase-mstk** [42-pong/42-pong#2]
PR　レビュワー割り当て通知
Discussion　起票通知　（必要なければwebhookでカテゴリーごとに通知するだけでいいかも）

**Comment by penguin2** [comment]
以下より、discussion 関連操作をトリガーとする workflow も作成できそうです。

https://docs.github.com/en/webhooks/webhook-events-and-payloads#discussion

**Comment by penguin2** [comment]
以下、dicussion 通知サンプルの共有です。

![discussion-notification-sample](https://github.com/user-attachments/assets/d5fe3a73-d396-48a6-a0e8-e1bb867694ef)
- [x] ランダム絵文字
- [x] ランダム形容詞
- [x] アナウンスの文章
- [x] everyone 通知
- [x] 10行目以降は ```...``` で置き換え

**Comment by penguin2** [comment]
次のように変更！

- [ ] ランダム絵文字
- [x] ランダム形容詞
- [x] アナウンスの文章
- [ ] everyone 通知
- [x] 10行目以降は ```...``` で置き換え
- [x] category がわかるように
