### ISSUE TITLE
[BE] github actionsでlinter, formatter, mypy走るように

### ISSUE THREAD

**Issue by ayase-mstk** [42-pong/42-pong#29]
Discussion link
- #16 

---
- ruffを使ってlinter, formatter
- mypyを使って型チェック
- workflowで上記が走るようにする

**Comment by ayase-mstk** [comment]
- lign-length: 89にする
- Makefileをbackendように作ってもいいかも

**Comment by habvi** [comment]
すみません、line-length 79 文字でした🙏
https://peps.python.org/pep-0008/#:~:text=spaces%20for%20indentation.-,Maximum%20Line%20Length,be%20limited%20to%2072%20characters.
