### ISSUE TITLE
coderabbit 無料版の導入　PRテンプレート作成

### ISSUE THREAD

**Issue by ayase-mstk** [42-pong/42-pong#33]
- PR を open するとその PR の sammary を自動で作成してくれる
- 今は PR template もあるので、template を coderabbit も考慮したものに変更する？

**Comment by weijuan82113** [comment]
[ask]
coderabbitはbackendのコードのみを確認してくれますか？
イメージとしてはpythonのみがPEP8のスタイルガイドがあり、
テンプレートはfrontとbackendの両方が使用するので、
衝突がないかを気になります。
